Repository hyperledger/avalon, pull requests merged in 2020-07, with the labels that each got.

#599 Remove command line workload configuration
  config/singleton_enclave_config.toml
  config/wpe_config.toml
  enclave_manager/avalon_enclave_manager/singleton/singleton_enclave_manager.py
  enclave_manager/avalon_enclave_manager/work_order_processor_manager.py
  enclave_manager/avalon_enclave_manager/wpe/wpe_enclave_manager.py
  tc/sgx/trusted_worker_manager/enclave/work_order_processor.cpp
Labels: bug

#606 Rephrase invalid workload error message in enclave
  tc/sgx/trusted_worker_manager/enclave/work_order_processor.cpp
Labels: bug

#614 FAQ: Add Graphene Enclave Manager ZMQ socket URL
  docs/FAQ.rst
Labels: documentation

#617 Correction to fabric proxy model doc
  docs/TestingFabricProxyModel.rst
Labels: documentation

#616 Add/Enhance function comments
  tc/sgx/trusted_worker_manager/enclave/kme/ext_work_order_info_kme.cpp
  tc/sgx/trusted_worker_manager/enclave/kme/ext_work_order_info_kme.h
Labels: documentation

#615 Verify EncryptionKey Signature from client
  common/crypto_utils/avalon_crypto_utils/signature.py
  common/python/utility/hex_utils.py
  examples/apps/generic_client/generic_client.py
  sdk/avalon_sdk/worker/worker_details.py
  tc/sgx/trusted_worker_manager/enclave/enclave_data.h
  tests/test_utility/test_hex_utils.py
Labels: enhancement

#620 Make Worker id config mandatory field
  docker/k8s/fabric/README.md
  docs/TestingBesuProxyModel.rst
  docs/TestingFabricProxyModel.rst
  docs/TestingGanacheProxyModel.rst
  examples/apps/echo/README.md
  examples/apps/echo/client/echo_client.py
  examples/apps/generic_client/README.md
  examples/apps/generic_client/eth_generic_client.py
  examples/apps/generic_client/fabric_generic_client.py
  examples/apps/generic_client/generic_client.py
  scripts/tcs_startup.sh
  tools/run_proxy_model_tests.sh
  tools/run_tests.sh
Labels: bug
