Repository hyperledger/avalon, pull requests merged in 2020-08, with the labels that each got.

#659 Encrypt outData in work order requests in listener mode
  common/crypto_utils/avalon_crypto_utils/signature.py
Labels: bug

#664 Update workload tutorial documentation
  docs/workload-tutorial/README.md
Labels: documentation

#600 Jsonschema library added
  BUILD.md
  blockchain_connector/docker/Dockerfile-ethereum
  blockchain_connector/docker/Dockerfile-fabric
  common/python/listener/base_jrpc_listener.py
  common/python/schema_validation/__init__.py
  common/python/schema_validation/data/WorkOrderGetResult.json
  common/python/schema_validation/data/WorkOrderReceiptCreate.json
  common/python/schema_validation/data/WorkOrderReceiptLookUp.json
  common/python/schema_validation/data/WorkOrderReceiptLookUpNext.json
  common/python/schema_validation/data/WorkOrderReceiptRetrieve.json
  common/python/schema_validation/data/WorkOrderReceiptUpdate.json
  common/python/schema_validation/data/WorkOrderReceiptUpdateRetrieve.json
  common/python/schema_validation/data/WorkOrderSubmit.json
  common/python/schema_validation/data/WorkerLookUp.json
  common/python/schema_validation/data/WorkerLookUpNext.json
  common/python/schema_validation/data/WorkerRetrieve.json
  common/python/schema_validation/data/sdk_WorkOrderSubmit.json
  common/python/schema_validation/data/sdk_inData.json
  common/python/schema_validation/data/tc_methods.json
  common/python/schema_validation/validate.py
  common/python/setup.py
  enclave_manager/Dockerfile
  enclave_manager/avalon_enclave_manager/wpe/wpe_requester.py
  examples/apps/echo/client/echo_client.py
  examples/apps/generic_client/base_generic_client.py
  examples/apps/generic_client/direct_model_generic_client.py
  examples/apps/generic_client/generic_client.py
  examples/apps/heart_disease_eval/client/heart_gui.py
  listener/Dockerfile
  listener/avalon_listener/tcs_work_order_handler.py
  listener/avalon_listener/tcs_work_order_handler_sync.py
  listener/avalon_listener/tcs_worker_registry_handler.py
  sdk/avalon_sdk/connector/direct/jrpc/jrpc_worker_registry.py
  sdk/avalon_sdk/work_order/work_order_params.py
  sdk/avalon_sdk/work_order/work_order_request_validator.py
  sdk/avalon_sdk/worker/worker_request_validator.py
  tests/json_requests/json_03.json
  tests/json_requests/json_06.json
  tests/json_requests/json_08.json
  tests/json_requests/json_10.json
  tests/json_requests/json_12.json
Labels: enhancement

#651 Update SGX sdk to latest version
  PREREQUISITES.md
  docker/Dockerfile
  enclave_manager/Dockerfile
  tc/sgx/trusted_worker_manager/enclave/CMakeVariables.txt
  tc/sgx/trusted_worker_manager/enclave_untrusted/enclave_bridge/CMakeLists.txt
  tc/sgx/trusted_worker_manager/enclave_untrusted/enclave_bridge/enclave.cpp
  tc/sgx/trusted_worker_manager/enclave_untrusted/enclave_bridge/enclave.h
  tc/sgx/trusted_worker_manager/enclave_untrusted/enclave_bridge/singleton/signup_singleton.cpp
Labels: enhancement
